import { type ComponentType, type SVGProps } from "react";
import {
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowLeftOnRectangleIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpTrayIcon,
  ArrowsRightLeftIcon,
  Bars3Icon,
  BellIcon,
  BoltIcon,
  BookOpenIcon,
  BookmarkIcon,
  BriefcaseIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftIcon,
  CheckCircleIcon,
  CheckIcon,
  CreditCardIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  CloudArrowUpIcon,
  Cog6ToothIcon,
  CpuChipIcon,
  ExclamationTriangleIcon,
  DocumentIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  FolderIcon,
  FolderPlusIcon,
  GlobeAltIcon,
  HeartIcon,
  InformationCircleIcon,
  LightBulbIcon,
  LockClosedIcon,
  MapIcon,
  MapPinIcon,
  MinusCircleIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  MusicalNoteIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PencilIcon,
  PhotoIcon,
  PlusIcon,
  PresentationChartBarIcon,
  QuestionMarkCircleIcon,
  ScaleIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  SignalIcon,
  SpeakerWaveIcon,
  SparklesIcon,
  SunIcon,
  MoonIcon,
  Squares2X2Icon,
  StarIcon,
  TagIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  ClipboardDocumentIcon,
  TrashIcon,
  UserGroupIcon,
  UserIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { BookmarkIcon as BookmarkSolidIcon } from "@heroicons/react/24/solid";

type HeroIcon = ComponentType<SVGProps<SVGSVGElement>>;

const iconMap: Record<string, HeroIcon> = {
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "bar-chart-2": ChartBarIcon,
  bell: BellIcon,
  ban: MinusCircleIcon,
  bookmark: BookmarkIcon,
  "bookmark-solid": BookmarkSolidIcon,
  "book-open": BookOpenIcon,
  brain: CpuChipIcon,
  briefcase: BriefcaseIcon,
  calendar: CalendarDaysIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  circle: MinusCircleIcon,
  "circle-check": CheckCircleIcon,
  cpu: CpuChipIcon,
  clipboard: ClipboardDocumentIcon,
  "clipboard-list": ClipboardDocumentListIcon,
  clock: ClockIcon,
  compass: GlobeAltIcon,
  "credit-card": CreditCardIcon,
  crown: StarIcon,
  download: ArrowDownTrayIcon,
  "external-link": ArrowTopRightOnSquareIcon,
  file: DocumentIcon,
  "file-audio": MusicalNoteIcon,
  "file-down": ArrowDownTrayIcon,
  "file-text": DocumentTextIcon,
  "file-type": DocumentIcon,
  folder: FolderIcon,
  "folder-plus": FolderPlusIcon,
  "git-branch": ArrowsRightLeftIcon,
  "git-compare": ArrowsRightLeftIcon,
  globe: GlobeAltIcon,
  grid: Squares2X2Icon,
  "grip-vertical": Bars3Icon,
  "help-circle": QuestionMarkCircleIcon,
  info: InformationCircleIcon,
  "image-down": PhotoIcon,
  "layout-grid": Squares2X2Icon,
  lightbulb: LightBulbIcon,
  list: Bars3Icon,
  loader: ArrowPathIcon,
  "loader-2": ArrowPathIcon,
  "loader-circle": ArrowPathIcon,
  lock: LockClosedIcon,
  "log-in": ArrowRightOnRectangleIcon,
  "log-out": ArrowLeftOnRectangleIcon,
  mail: EnvelopeIcon,
  "message-circle": ChatBubbleLeftIcon,
  "message-square": ChatBubbleBottomCenterTextIcon,
  mic: MicrophoneIcon,
  "mic-off": MicrophoneIcon,
  pencil: PencilIcon,
  podcast: SpeakerWaveIcon,
  plus: PlusIcon,
  presentation: PresentationChartBarIcon,
  scale: ScaleIcon,
  search: MagnifyingGlassIcon,
  "search-x": MagnifyingGlassIcon,
  paperclip: PaperClipIcon,
  send: PaperAirplaneIcon,
  settings: Cog6ToothIcon,
  "shield-alert": ShieldExclamationIcon,
  "shield-check": ShieldExclamationIcon,
  sparkles: SparklesIcon,
  sun: SunIcon,
  moon: MoonIcon,
  "sticky-note": DocumentTextIcon,
  "thumbs-up": HandThumbUpIcon,
  "thumbs-down": HandThumbDownIcon,
  "trash-2": TrashIcon,
  "triangle-alert": ExclamationTriangleIcon,
  upload: ArrowUpTrayIcon,
  "upload-cloud": CloudArrowUpIcon,
  user: UserIcon,
  users: UserGroupIcon,
  x: XMarkIcon,
  zap: BoltIcon,
  target: MapPinIcon,
  heart: HeartIcon,
  map: MapIcon,
  "alert-triangle": ExclamationTriangleIcon,
  shield: ShieldCheckIcon,
  tag: TagIcon,
  activity: SignalIcon,
  "trending-up": ChartBarIcon,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
}

export function Icon({ name, size = 18, className }: IconProps) {
  const HeroComponent = iconMap[name];
  if (!HeroComponent) return null;
  return (
    <HeroComponent
      width={size}
      height={size}
      className={className}
      style={{ width: size, height: size }}
    />
  );
}
